<#
.SYNOPSIS
    Generates the Azure Function App entry point from the shared runbook source.

.DESCRIPTION
    Reads azure/runbook-source.ps1, replaces the parameter block and Automation
    variable resolution with Function App equivalents (timer trigger parameter,
    environment variable configuration), inlines the canonical shared helper
    block from shared-helpers.ps1, and writes the assembled result to
    azure/function-app/ExportAndGenerate/run.ps1.

    This keeps a single source of truth for the dashboard pipeline logic while
    producing both an Automation runbook artifact and a Function App artifact.

.EXAMPLE
    .\azure\Build-FunctionApp.ps1
#>

#Requires -Version 7.0

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Path $PSScriptRoot -Parent
$buildSharedHelpersPath = Join-Path -Path $repoRoot -ChildPath 'Build-SharedHelpers.ps1'
$sharedHelpersPath = Join-Path -Path $repoRoot -ChildPath 'shared-helpers.ps1'
$runbookSourcePath = Join-Path -Path $PSScriptRoot -ChildPath 'runbook-source.ps1'
$outputPath = Join-Path -Path $PSScriptRoot -ChildPath 'function-app' | Join-Path -ChildPath 'ExportAndGenerate' | Join-Path -ChildPath 'run.ps1'

# -------------------------------------------------------------------------
# Validation
# -------------------------------------------------------------------------

if (-not (Test-Path -Path $buildSharedHelpersPath -PathType Leaf)) {
    throw "Shared helper build script not found: $buildSharedHelpersPath"
}

if (-not (Test-Path -Path $runbookSourcePath -PathType Leaf)) {
    throw "Runbook source file not found: $runbookSourcePath"
}

# -------------------------------------------------------------------------
# Build shared helpers
# -------------------------------------------------------------------------

& $buildSharedHelpersPath

if (-not (Test-Path -Path $sharedHelpersPath -PathType Leaf)) {
    throw "Shared helper file not found after build: $sharedHelpersPath"
}

# -------------------------------------------------------------------------
# Read sources
# -------------------------------------------------------------------------

$runbookSource = Get-Content -Path $runbookSourcePath -Raw
$sharedHelpers = Get-Content -Path $sharedHelpersPath -Raw
$lineEnding = if ($runbookSource.Contains("`r`n")) { "`r`n" } else { "`n" }

# -------------------------------------------------------------------------
# Replace header (comment block + param block + preference settings)
# -------------------------------------------------------------------------

# The header in runbook-source.ps1 spans from the BOM/start through the
# $ProgressPreference line.  We replace everything up to (and including)
# that line with the Function App timer-trigger entry point.

$functionAppHeader = @'
<#
.SYNOPSIS
    Timer-triggered Azure Function for the Defender vulnerability dashboard pipeline.

.DESCRIPTION
    Generated by azure/Build-FunctionApp.ps1 from azure/runbook-source.ps1 and
    shared-helpers.ps1.  Do not edit this file directly — edit the source files
    and re-run the build script.

    Runs the same pipeline as the Azure Automation runbook but inside an Azure
    Function App on the Flex Consumption plan.  Configuration is read from
    Function App settings (environment variables) instead of Automation variables.

    Environment variables (Function App settings):
        STORAGE_ACCOUNT_NAME        - (required) Azure Storage account name
        DASHBOARD_DELIVERY_MODE     - SelfContained (default) or Hosted
        INCLUDE_ADVANCED_HUNTING    - true (default) or false
        USE_EXISTING_EXPORTS_ONLY   - true or false (default)
        EXPORT_TARGET               - BlobStorage (default), SharePoint, or StaticWebApp
#>

#Requires -Version 7.0

param($Timer)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# Read configuration from Function App settings (environment variables)
$StorageAccountName = $env:STORAGE_ACCOUNT_NAME
$DashboardDeliveryMode = if ($env:DASHBOARD_DELIVERY_MODE) { $env:DASHBOARD_DELIVERY_MODE } else { 'SelfContained' }
$IncludeAdvancedHunting = ($env:INCLUDE_ADVANCED_HUNTING -ne 'false')
$UseExistingExportsOnly = ($env:USE_EXISTING_EXPORTS_ONLY -eq 'true')
$Export = if ($env:EXPORT_TARGET) { $env:EXPORT_TARGET } else { 'BlobStorage' }

if ($Timer.IsPastDue) {
    Write-Output "Timer function ran past due!"
}
'@

# Match from the start of the file (possibly with BOM) through the
# $ProgressPreference = 'SilentlyContinue' line.
$headerPattern = "(?s)\A\uFEFF?.*?\`$ProgressPreference\s*=\s*'SilentlyContinue'"
if ($runbookSource -notmatch $headerPattern) {
    throw "Could not locate the header section (through `$ProgressPreference) in runbook-source.ps1."
}
$assembled = $runbookSource -replace $headerPattern, ($functionAppHeader -replace '\$', '$$')

# -------------------------------------------------------------------------
# Replace Automation variable resolution with Function App config
# -------------------------------------------------------------------------

# In Stage A the runbook resolves StorageAccountName and DashboardDeliveryMode
# from Automation variables.  We replace that block with env-var validation.

$automationVarStart = '    # Resolve StorageAccountName from Automation variable if not provided as parameter'
$automationVarEnd = '    Write-Output "  Dashboard delivery mode: $DashboardDeliveryMode"'

$functionAppConfig = @'
    # Configuration already resolved from Function App settings above
    if (-not $StorageAccountName) {
        throw "STORAGE_ACCOUNT_NAME app setting is not configured."
    }
    Write-Output "  Storage account: $StorageAccountName"

    if ($DashboardDeliveryMode -notin @('SelfContained', 'Hosted')) {
        throw "DASHBOARD_DELIVERY_MODE must be SelfContained or Hosted. Received '$DashboardDeliveryMode'."
    }
    Write-Output "  Dashboard delivery mode: $DashboardDeliveryMode"
'@

$startIdx = $assembled.IndexOf($automationVarStart)
$endIdx = $assembled.IndexOf($automationVarEnd)

if ($startIdx -lt 0 -or $endIdx -lt 0) {
    throw "Could not locate the Automation variable resolution block in runbook-source.ps1."
}

$endIdx += $automationVarEnd.Length
$assembled = $assembled.Substring(0, $startIdx) + $functionAppConfig + $assembled.Substring($endIdx)

# -------------------------------------------------------------------------
# Inline shared helpers at the marker
# -------------------------------------------------------------------------

$marker = @'
# =============================================================================
# SHARED HELPERS INSERTED BY azure/Build-Runbook.ps1
# =============================================================================
'@

$normalizedMarker = $marker -replace "`r?`n", $lineEnding
$sharedHelpersText = if ($sharedHelpers -is [System.Array]) {
    @($sharedHelpers) -join $lineEnding
}
else {
    [string]$sharedHelpers
}
$normalizedSharedHelpers = ($sharedHelpersText -replace "`r?`n", $lineEnding).TrimEnd()

if (-not $assembled.Contains($normalizedMarker)) {
    throw 'Source is missing the shared helper marker.'
}

$assembled = $assembled.Replace($normalizedMarker, $normalizedSharedHelpers + $lineEnding + $lineEnding)

# -------------------------------------------------------------------------
# Write output
# -------------------------------------------------------------------------

$outputDir = Split-Path -Path $outputPath -Parent
if (-not (Test-Path -Path $outputDir)) {
    New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
}

[System.IO.File]::WriteAllText($outputPath, $assembled, [System.Text.UTF8Encoding]::new($true))

Write-Output "Generated function app entry point: $outputPath"
