<#
.SYNOPSIS
    Unified Azure Automation runbook for the Defender vulnerability dashboard pipeline.

.DESCRIPTION
    This runbook performs the complete dashboard pipeline in a single execution:
    
    1. Authenticates via Managed Identity
    2. Downloads historical export data and templates from Azure Blob Storage
    3. Exports fresh vulnerability, machine, and Advanced Hunting data from MDE APIs
    4. Generates the self-contained HTML dashboard
    5. Uploads results back to Blob Storage (compressed)
    
    The published runbook is generated by azure/Build-Runbook.ps1 from this
    source file plus shared-helpers.ps1 so the distributed artifact remains
    fully self-contained with no external script dependencies.
    
    Export files are stored as .json.gz (GZip compressed) in blob storage to minimize
    storage costs and download bandwidth. They are decompressed in the ephemeral sandbox
    for processing and recompressed before upload.

.PARAMETER StorageAccountName
    Name of the Azure Storage account containing the exports, templates, and dashboards containers.
    If not provided, reads from the 'StorageAccountName' Automation variable.

.PARAMETER IncludeAdvancedHunting
    Include Advanced Hunting data for CVE enrichment (PublishedDate, Description, EPSS).
    Requires AdvancedQuery.Read.All permission on the Managed Identity. Default: true

.PARAMETER Export
    Export target for the generated dashboard. Default: BlobStorage
    Options: BlobStorage, SharePoint, StaticWebApp

.NOTES
    Author: Nathan McNulty
    Runtime: PowerShell 7.4 (Azure Automation - custom runtime environment)
    
    Prerequisites:
    - System-assigned Managed Identity with:
      - Storage Blob Data Contributor on the Storage Account
      - MDE app roles: Machine.Read.All, Vulnerability.Read.All, AdvancedQuery.Read.All
    - Templates uploaded to the 'templates' blob container via Upload-Templates.ps1
#>

#Requires -Version 7.0

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$StorageAccountName,

    [Parameter(Mandatory = $false)]
    [bool]$IncludeAdvancedHunting = $true,

    [Parameter(Mandatory = $false)]
    [ValidateSet('BlobStorage', 'SharePoint', 'StaticWebApp')]
    [string]$Export = 'BlobStorage'
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# =============================================================================
# CONSTANTS
# =============================================================================

$Script:MdeApiUrl = 'https://api.securitycenter.microsoft.com'
$Script:MdeBulkExportUrl = 'https://api.security.microsoft.com/api/machines/SoftwareVulnerabilitiesExport'
$Script:AdvancedHuntingUrl = 'https://api.security.microsoft.com/api/advancedqueries/run'
$Script:BlobApiVersion = '2021-12-02'

$Script:BlobContainers = @{
    Exports    = 'exports'
    Templates  = 'templates'
    Dashboards = 'dashboards'
}

$Script:BlobAccessTiers = @{
    Exports    = 'Hot'
    Templates  = 'Cool'
    Dashboards = 'Hot'
}

$Script:LibraryConfig = @{
    ChartJs = @{
        Url = "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.js"
        Name = "Chart.js"
        Critical = $true
    }
    PdfMake = @{
        Url = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"
        Name = "pdfmake"
        Critical = $false
    }
    VfsFonts = @{
        Url = "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.min.js"
        Name = "vfs_fonts"
        Critical = $false
    }
    Html2Pdf = @{
        Url = "https://cdn.jsdelivr.net/npm/html2pdf.js@0.10.1/dist/html2pdf.bundle.min.js"
        Name = "html2pdf.js"
        Critical = $false
    }
    Html2Canvas = @{
        Url = "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
        Name = "html2canvas"
        Critical = $false
    }
    Pako = @{
        Url = "https://cdn.jsdelivr.net/npm/pako@2.1.0/dist/pako.min.js"
        Name = "pako"
        Critical = $false
    }
}


# =============================================================================
# SHARED HELPERS INSERTED BY azure/Build-Runbook.ps1
# =============================================================================

# =============================================================================
# HELPER FUNCTIONS - DIAGNOSTICS
# =============================================================================

function Write-MemoryUsage {
    <#
    .SYNOPSIS
        Writes current process memory usage to output for monitoring in Azure Automation.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [string]$Label = ""
    )

    $proc = [System.Diagnostics.Process]::GetCurrentProcess()
    $workingSetMB = [math]::Round($proc.WorkingSet64 / 1MB, 1)
    $gcHeapMB     = [math]::Round([System.GC]::GetTotalMemory($false) / 1MB, 1)
    $prefix = if ($Label) { "[$Label] " } else { "" }
    Write-Output "  ${prefix}Memory — Working set: ${workingSetMB}MB  |  GC heap: ${gcHeapMB}MB"
}

# =============================================================================
# HELPER FUNCTIONS - TOKEN MANAGEMENT
# =============================================================================

function Get-PlainToken {
    <#
    .SYNOPSIS
        Gets a plain-text bearer token using Get-AzAccessToken -AsSecureString.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$ResourceUrl
    )

    $tokenResponse = Get-AzAccessToken -ResourceUrl $ResourceUrl -AsSecureString
    $ssPtr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($tokenResponse.Token)

    try { return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ssPtr) }
    finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ssPtr) }
}

# =============================================================================
# HELPER FUNCTIONS - GZIP COMPRESSION
# =============================================================================

function Compress-GzipFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$InputPath,

        [Parameter(Mandatory = $true)]
        [string]$OutputPath
    )

    $inputStream = $null
    $outputStream = $null
    $gzipStream = $null
    try {
        $inputStream = [System.IO.File]::OpenRead($InputPath)
        $outputStream = [System.IO.File]::Create($OutputPath)
        $gzipStream = [System.IO.Compression.GZipStream]::new($outputStream, [System.IO.Compression.CompressionLevel]::Optimal)
        $inputStream.CopyTo($gzipStream)
    }
    finally {
        if ($gzipStream) { $gzipStream.Dispose() }
        if ($outputStream) { $outputStream.Dispose() }
        if ($inputStream) { $inputStream.Dispose() }
    }
}

function Expand-GzipFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$InputPath,

        [Parameter(Mandatory = $true)]
        [string]$OutputPath
    )

    $inputStream = $null
    $gzipStream = $null
    $outputStream = $null
    try {
        $inputStream = [System.IO.File]::OpenRead($InputPath)
        $gzipStream = [System.IO.Compression.GZipStream]::new($inputStream, [System.IO.Compression.CompressionMode]::Decompress)
        $outputStream = [System.IO.File]::Create($OutputPath)
        $gzipStream.CopyTo($outputStream)
    }
    finally {
        if ($outputStream) { $outputStream.Dispose() }
        if ($gzipStream) { $gzipStream.Dispose() }
        if ($inputStream) { $inputStream.Dispose() }
    }
}

function Test-GzipSupport {
    [CmdletBinding()]
    param()

    try {
        $testBytes = [System.Text.Encoding]::UTF8.GetBytes('GZip test data')
        $memStream = [System.IO.MemoryStream]::new()
        $gzipStream = [System.IO.Compression.GZipStream]::new($memStream, [System.IO.Compression.CompressionMode]::Compress)
        $gzipStream.Write($testBytes, 0, $testBytes.Length)
        $gzipStream.Dispose()
        $compressed = $memStream.ToArray()
        $memStream.Dispose()

        $memStream2 = [System.IO.MemoryStream]::new($compressed)
        $gzipStream2 = [System.IO.Compression.GZipStream]::new($memStream2, [System.IO.Compression.CompressionMode]::Decompress)
        $resultStream = [System.IO.MemoryStream]::new()
        $gzipStream2.CopyTo($resultStream)
        $gzipStream2.Dispose()
        $memStream2.Dispose()
        $result = [System.Text.Encoding]::UTF8.GetString($resultStream.ToArray())
        $resultStream.Dispose()

        return ($result -eq 'GZip test data')
    }
    catch {
        return $false
    }
}

# =============================================================================
# HELPER FUNCTIONS - BLOB STORAGE REST API
# =============================================================================

function Get-BlobHeader {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$StorageToken
    )

    return @{
        'Authorization' = "Bearer $StorageToken"
        'x-ms-version'  = $Script:BlobApiVersion
    }
}

function Get-BlobErrorStatusCode {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [System.Management.Automation.ErrorRecord]$ErrorRecord
    )

    $response = $ErrorRecord.Exception.PSObject.Properties['Response']?.Value
    if ($null -ne $response) {
        $statusCode = $response.PSObject.Properties['StatusCode']?.Value
        if ($statusCode -is [int]) {
            return $statusCode
        }
        if ($null -ne $statusCode -and $statusCode.PSObject.Properties['value__']) {
            return [int]$statusCode.value__
        }
        if ($null -ne $statusCode) {
            $parsedStatusCode = 0
            if ([int]::TryParse($statusCode.ToString(), [ref]$parsedStatusCode)) {
                return $parsedStatusCode
            }
        }
    }

    $statusCodeValue = $ErrorRecord.Exception.PSObject.Properties['StatusCode']?.Value
    if ($statusCodeValue -is [int]) {
        return $statusCodeValue
    }
    if ($null -ne $statusCodeValue -and $statusCodeValue.PSObject.Properties['value__']) {
        return [int]$statusCodeValue.value__
    }

    $message = [string]$ErrorRecord.Exception.Message
    if ($message -match '\b(\d{3})\b') {
        return [int]$Matches[1]
    }

    return $null
}

function Get-BlobList {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AccountName,

        [Parameter(Mandatory = $true)]
        [string]$Container,

        [Parameter(Mandatory = $true)]
        [string]$StorageToken,

        [string]$Prefix
    )

    $baseUrl = "https://$AccountName.blob.core.windows.net"
    $uri = "$baseUrl/$Container`?restype=container&comp=list"
    if ($Prefix) {
        $uri += "&prefix=$Prefix"
    }

    $headers = Get-BlobHeader -StorageToken $StorageToken

    try {
        $webResponse = Invoke-WebRequest -Uri $uri -Headers $headers -Method Get
        $xmlContent = $webResponse.Content.TrimStart([char]0xFEFF)
        $xmlDoc = [System.Xml.XmlDocument]::new()
        $xmlDoc.LoadXml($xmlContent)
        $blobsNode = $xmlDoc.SelectSingleNode('/EnumerationResults/Blobs')
        if ($null -eq $blobsNode) {
            return @()
        }

        $blobNodes = @($blobsNode.SelectNodes('Blob'))
        if ($blobNodes.Count -eq 0) {
            return @()
        }

        return @($blobNodes | ForEach-Object { $_.SelectSingleNode('Name')?.InnerText } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    }
    catch {
        $statusCode = Get-BlobErrorStatusCode -ErrorRecord $_
        if ($statusCode -eq 404) {
            return @()
        }
        throw "Failed to list blobs in '$Container': $_"
    }
}

function Get-BlobContent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AccountName,

        [Parameter(Mandatory = $true)]
        [string]$Container,

        [Parameter(Mandatory = $true)]
        [string]$BlobName,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath,

        [Parameter(Mandatory = $true)]
        [string]$StorageToken
    )

    $baseUrl = "https://$AccountName.blob.core.windows.net"
    $uri = "$baseUrl/$Container/$BlobName"
    $headers = Get-BlobHeader -StorageToken $StorageToken

    $parentDir = Split-Path -Path $DestinationPath -Parent
    if (-not (Test-Path -Path $parentDir)) {
        New-Item -Path $parentDir -ItemType Directory -Force | Out-Null
    }

    Invoke-RestMethod -Uri $uri -Headers $headers -Method Get -OutFile $DestinationPath
}

function Set-BlobContent {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AccountName,

        [Parameter(Mandatory = $true)]
        [string]$Container,

        [Parameter(Mandatory = $true)]
        [string]$BlobName,

        [Parameter(Mandatory = $true)]
        [string]$SourcePath,

        [Parameter(Mandatory = $true)]
        [string]$StorageToken,

        [string]$ContentType = 'application/octet-stream',

        [ValidateSet('Hot', 'Cool', 'Cold', 'Archive')]
        [string]$AccessTier
    )

    $baseUrl = "https://$AccountName.blob.core.windows.net"
    $uri = "$baseUrl/$Container/$BlobName"
    $headers = Get-BlobHeader -StorageToken $StorageToken
    $headers['x-ms-blob-type'] = 'BlockBlob'
    if ($AccessTier) {
        $headers['x-ms-access-tier'] = $AccessTier
    }

    Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -InFile $SourcePath -ContentType $ContentType
}

function Test-BlobExistence {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AccountName,

        [Parameter(Mandatory = $true)]
        [string]$Container,

        [Parameter(Mandatory = $true)]
        [string]$BlobName,

        [Parameter(Mandatory = $true)]
        [string]$StorageToken
    )

    $baseUrl = "https://$AccountName.blob.core.windows.net"
    $uri = "$baseUrl/$Container/$BlobName"
    $headers = Get-BlobHeader -StorageToken $StorageToken

    try {
        Invoke-WebRequest -Uri $uri -Headers $headers -Method Head -ErrorAction Stop | Out-Null
        return $true
    }
    catch {
        return $false
    }
}

function Remove-Blob {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '')]
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$AccountName,

        [Parameter(Mandatory = $true)]
        [string]$Container,

        [Parameter(Mandatory = $true)]
        [string]$BlobName,

        [Parameter(Mandatory = $true)]
        [string]$StorageToken
    )

    $baseUrl = "https://$AccountName.blob.core.windows.net"
    $uri = "$baseUrl/$Container/$BlobName"
    $headers = Get-BlobHeader -StorageToken $StorageToken

    try {
        Invoke-WebRequest -Uri $uri -Headers $headers -Method Delete -ErrorAction Stop | Out-Null
    }
    catch {
        $statusCode = Get-BlobErrorStatusCode -ErrorRecord $_
        if ($statusCode -ne 404) {
            throw "Failed to delete blob '$BlobName' from '$Container': $_"
        }
    }
}

# =============================================================================
# HELPER FUNCTIONS - EXPORT TARGETS
# =============================================================================

function Export-ToBlobStorage {
    <#
    .SYNOPSIS
        Uploads new export files (compressed) and dashboard HTML to blob storage.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$AccountName,

        [Parameter(Mandatory)]
        [string]$StorageToken,

        [Parameter(Mandatory)]
        [string]$ExportsPath,

        [Parameter(Mandatory)]
        [string]$DashboardPath,

        [string[]]$LegacyMachineBlobNames = @(),

        [string[]]$LegacyAdvancedHuntingBlobNames = @(),

        [string[]]$LegacyVulnerabilityBlobNames = @(),

        [bool]$UseGzip = $true
    )

    Write-Output "`nUploading results to blob storage..."

    # Upload new export files (compressed)
    $exportFiles = Get-ChildItem -Path $ExportsPath -File | Where-Object { $_.Extension -in @('.json', '.gz') }
    foreach ($file in $exportFiles) {
        $isCanonicalStoreFile = $file.Name -in @($Script:MachineCurrentFileName, $Script:MachineHistoryFileName, $Script:AdvancedHuntingCurrentFileName, $Script:VulnCurrentFileName)
        if ($file.Name -like 'VulnHistory_*.json.gz') {
            $isCanonicalStoreFile = $true
        }
        if ($UseGzip) {
            if ($file.Extension -eq '.gz') {
                $blobName = $file.Name
                Write-Output "  Uploading $blobName..."
                Set-BlobContent -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -SourcePath $file.FullName -StorageToken $StorageToken -ContentType 'application/gzip' -AccessTier $Script:BlobAccessTiers.Exports
                continue
            }

            $gzPath = "$($file.FullName).gz"
            $blobName = "$($file.Name).gz"

            # Skip if this blob already exists
            if ((-not $isCanonicalStoreFile) -and (Test-BlobExistence -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -StorageToken $StorageToken)) {
                Write-Output "  Skipping $blobName (already exists)"
                continue
            }

            Write-Output "  Compressing and uploading $($file.Name)..."
            Compress-GzipFile -InputPath $file.FullName -OutputPath $gzPath
            $originalSize = (Get-Item $file.FullName).Length
            $compressedSize = (Get-Item $gzPath).Length
            $ratio = if ($originalSize -gt 0) { [math]::Round((1 - $compressedSize / $originalSize) * 100, 1) } else { 0 }
            Write-Output "    Compressed: $([math]::Round($originalSize/1KB))KB -> $([math]::Round($compressedSize/1KB))KB ($ratio% reduction)"

            Set-BlobContent -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -SourcePath $gzPath -StorageToken $StorageToken -ContentType 'application/gzip' -AccessTier $Script:BlobAccessTiers.Exports
            Remove-Item -Path $gzPath -Force
        }
        else {
            $blobName = $file.Name
            if ((-not $isCanonicalStoreFile) -and (Test-BlobExistence -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -StorageToken $StorageToken)) {
                Write-Output "  Skipping $blobName (already exists)"
                continue
            }
            Write-Output "  Uploading $($file.Name)..."
            Set-BlobContent -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -SourcePath $file.FullName -StorageToken $StorageToken -ContentType 'application/json' -AccessTier $Script:BlobAccessTiers.Exports
        }
    }

    foreach ($legacyBlob in $LegacyMachineBlobNames) {
        Write-Output "  Removing legacy machine snapshot blob $legacyBlob..."
        Remove-Blob -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $legacyBlob -StorageToken $StorageToken
    }

    foreach ($legacyBlob in $LegacyAdvancedHuntingBlobNames) {
        Write-Output "  Removing legacy Advanced Hunting snapshot blob $legacyBlob..."
        Remove-Blob -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $legacyBlob -StorageToken $StorageToken
    }

    foreach ($legacyBlob in $LegacyVulnerabilityBlobNames) {
        Write-Output "  Removing legacy vulnerability snapshot blob $legacyBlob..."
        Remove-Blob -AccountName $AccountName -Container $Script:BlobContainers.Exports -BlobName $legacyBlob -StorageToken $StorageToken
    }

    # Upload dashboard HTML (always uncompressed)
    if (Test-Path $DashboardPath) {
        Write-Output "  Uploading VulnerabilityDashboard.html..."
        Set-BlobContent -AccountName $AccountName -Container $Script:BlobContainers.Dashboards -BlobName "VulnerabilityDashboard.html" -SourcePath $DashboardPath -StorageToken $StorageToken -ContentType 'text/html' -AccessTier $Script:BlobAccessTiers.Dashboards
        Write-Output "  Dashboard uploaded to '$($Script:BlobContainers.Dashboards)/VulnerabilityDashboard.html'"
    }
}

function Export-ToSharePoint {
    <#
    .SYNOPSIS
        Uploads dashboard to SharePoint Online. (Not yet implemented)
    #>
    [CmdletBinding()]
    param(
        [string]$DashboardPath
    )

    Write-Warning "SharePoint export is not yet implemented."
    Write-Output "  To implement: Upload via Microsoft Graph API using Sites.ReadWrite.All permission."
    Write-Output "  The Managed Identity would need the Sites.ReadWrite.All app role on the Microsoft Graph SP."
    $null = $DashboardPath
}

function Export-ToStaticWebApp {
    <#
    .SYNOPSIS
        Deploys dashboard to Azure Static Web Apps. (Not yet implemented)
    #>
    [CmdletBinding()]
    param(
        [string]$DashboardPath
    )

    Write-Warning "Static Web App export is not yet implemented."
    Write-Output "  To implement: Use the SWA CLI (swa deploy) with a deployment token."
    Write-Output "  Note: Azure Automation sandboxes do not have Node.js; consider a Hybrid Runbook Worker."
    $null = $DashboardPath
}

# =============================================================================
# MAIN PIPELINE
# =============================================================================

try {
    Write-Output "========================================"
    Write-Output "  Vulnerability Dashboard Pipeline"
    Write-Output "========================================"
    Write-Output "  Started: $(([datetime]::UtcNow).ToString('yyyy-MM-dd HH:mm:ss')) UTC"
    Write-MemoryUsage -Label "Start"

    # -----------------------------------------------------------------
    # Stage A: Authenticate
    # -----------------------------------------------------------------
    Write-Output "`n--- Stage A: Authentication ---"

    Write-Output "Connecting with Managed Identity..."
    Connect-AzAccount -Identity | Out-Null
    Write-Output "  Connected successfully"

    # Resolve StorageAccountName from Automation variable if not provided as parameter
    if (-not $StorageAccountName) {
        Write-Output "  Reading StorageAccountName from Automation variable..."
        $StorageAccountName = Get-AutomationVariable -Name 'StorageAccountName'
        if (-not $StorageAccountName) {
            throw "StorageAccountName not provided and Automation variable not found."
        }
    }
    Write-Output "  Storage account: $StorageAccountName"

    Write-Output "  Acquiring tokens..."
    $storageToken = Get-PlainToken -ResourceUrl 'https://storage.azure.com/'
    $mdeToken = Get-PlainToken -ResourceUrl 'https://api.securitycenter.microsoft.com'
    $mdeHeaders = Get-MdeHeaderCollection -AccessToken $mdeToken
    Write-Output "  Tokens acquired"

    # Test GZip support
    $useGzip = Test-GzipSupport
    if ($useGzip) {
        Write-Output "  GZip compression: supported"
    }
    else {
        Write-Warning "GZip compression not available in this runtime. Files will be stored uncompressed."
    }

    Write-MemoryUsage -Label "Post-Auth"

    # -----------------------------------------------------------------
    # Stage B: Download historical data from blob storage
    # -----------------------------------------------------------------
    Write-Output "`n--- Stage B: Download historical data ---"

    $tempRoot = Join-Path -Path $env:TEMP -ChildPath "dashboard-pipeline-$(Get-Date -Format 'yyyyMMddHHmmss')"
    $tempExports = Join-Path -Path $tempRoot -ChildPath "exports"
    $tempTemplates = Join-Path -Path $tempRoot -ChildPath "templates"
    $tempDashboards = Join-Path -Path $tempRoot -ChildPath "dashboards"

    New-Item -Path $tempExports -ItemType Directory -Force | Out-Null
    New-Item -Path $tempTemplates -ItemType Directory -Force | Out-Null
    New-Item -Path $tempDashboards -ItemType Directory -Force | Out-Null

    # Download historical export files
    Write-Output "Downloading historical exports..."
    $existingBlobs = @(Get-BlobList -AccountName $StorageAccountName -Container $Script:BlobContainers.Exports -StorageToken $storageToken)
    $legacyMachineBlobs = @($existingBlobs | Where-Object { $_ -match '^Machines_\d{4}-\d{2}-\d{2}\.json(\.gz)?$' })
    $legacyAdvancedHuntingBlobs = @($existingBlobs | Where-Object { $_ -match '^AdvancedHunting_\d+_\d{4}-\d{2}-\d{2}\.json(\.gz)?$' })
    $legacyVulnerabilityBlobs = @($existingBlobs | Where-Object { $_ -match '^VulnExport_\d+_\d{4}-\d{2}-\d{2}\.json(\.gz)?$' })
    Write-Output "  Found $($existingBlobs.Count) existing blob(s)"

    foreach ($blobName in $existingBlobs) {
        $localFile = Join-Path -Path $tempExports -ChildPath $blobName
        Write-Output "  Downloading $blobName..."
        Get-BlobContent -AccountName $StorageAccountName -Container $Script:BlobContainers.Exports -BlobName $blobName -DestinationPath $localFile -StorageToken $storageToken

        # Decompress .gz files
        if ($blobName -match '^(VulnExport_current\.json\.gz|VulnHistory_\d{4}\.json\.gz|Machines_Current\.json\.gz|Machines_History\.json\.gz|AdvancedHunting_Current\.json\.gz)$') {
            continue
        }

        if ($blobName -match '\.json\.gz$') {
            $jsonFile = $localFile -replace '\.gz$', ''
            Write-Output "    Decompressing..."
            Expand-GzipFile -InputPath $localFile -OutputPath $jsonFile
            Remove-Item -Path $localFile -Force
        }
    }

    # Download templates
    Write-Output "Downloading templates..."
    $templateBlobs = @(Get-BlobList -AccountName $StorageAccountName -Container $Script:BlobContainers.Templates -StorageToken $storageToken)

    if ($templateBlobs.Count -eq 0) {
        throw "No templates found in '$($Script:BlobContainers.Templates)' container. Run Upload-Templates.ps1 first."
    }

    foreach ($blobName in $templateBlobs) {
        $localFile = Join-Path -Path $tempTemplates -ChildPath $blobName
        Write-Output "  Downloading $blobName..."
        Get-BlobContent -AccountName $StorageAccountName -Container $Script:BlobContainers.Templates -BlobName $blobName -DestinationPath $localFile -StorageToken $storageToken
    }

    Write-MemoryUsage -Label "Post-BlobDownload"

    # -----------------------------------------------------------------
    # Stage C: Export fresh MDE data
    # -----------------------------------------------------------------
    Write-Output "`n--- Stage C: Export fresh MDE data ---"

    # Bulk vulnerability export
    Write-Output 'Requesting bulk vulnerability export...'
    $bulkExport = Invoke-MdeBulkVulnerabilitySnapshotDownload -Headers $mdeHeaders -OutputPath $tempExports -ExportUrl $Script:MdeBulkExportUrl
    Write-Output "  Downloading $($bulkExport.ExportFileCount) export file(s)..."
    foreach ($downloadedFile in $bulkExport.DownloadedFiles) {
        Write-Output "  Downloading $(Split-Path -Leaf $downloadedFile)..."
    }

    Write-Output "Updating vulnerability current/history store..."
    $vulnStore = Update-VulnStoreFromLegacySnapshot -BasePath $tempExports
    Publish-VulnStore -BasePath $tempExports -Store $vulnStore

    # Machine data
    Write-Output 'Exporting machine data from MDE API...'
    $machineExport = Invoke-MdeMachineStoreRefresh -Headers $mdeHeaders -OutputPath $tempExports -BaseApiUrl $Script:MdeApiUrl
    if ($machineExport.MigratedLegacy) {
        Write-Output '  Migrated legacy machine snapshots to current/history store'
    }
    $machineOutputFiles = @($machineExport.OutputFiles | ForEach-Object { Split-Path -Leaf $_ })
    Write-Output "  Saved machine current/history store to $($machineOutputFiles -join ' and ')"

    # Advanced Hunting (optional)
    if ($IncludeAdvancedHunting) {
        Write-Output 'Exporting Advanced Hunting data...'
        $advancedHuntingExport = Invoke-MdeAdvancedHuntingStoreRefresh -Headers $mdeHeaders -OutputPath $tempExports -QueryUrl $Script:AdvancedHuntingUrl
        if (-not $advancedHuntingExport.Success) {
            Write-Warning 'Advanced Hunting query returned no results.'
        }
        else {
            if ($advancedHuntingExport.MigratedLegacy) {
                Write-Output '  Migrated legacy Advanced Hunting snapshots to current cache'
            }
            Write-Output "  Saved Advanced Hunting cache to $(Split-Path -Leaf $advancedHuntingExport.OutputFile)"
        }
    }
    else {
        Write-Output "Skipping Advanced Hunting export (IncludeAdvancedHunting = false)"
    }

    Write-MemoryUsage -Label "Post-MdeExport"

    # -----------------------------------------------------------------
    # Stage D: Generate dashboard
    # -----------------------------------------------------------------
    Write-Output "`n--- Stage D: Generate dashboard ---"

    # Step 1: Read machine and Advanced Hunting data
    $machines = Read-MachineData -Path $tempExports
    $advancedHuntingData = Read-AdvancedHuntingData -Path $tempExports

    # Step 2 (skipped): vulnerability files are streamed directly inside ConvertTo-NormalizedData

    # Step 3: Download JavaScript libraries
    Write-Output "Downloading JavaScript libraries..."
    $lib = $Script:LibraryConfig.ChartJs
    $chartJsContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $lib.Critical

    $lib = $Script:LibraryConfig.PdfMake
    $pdfmakeContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $lib.Critical

    $lib = $Script:LibraryConfig.VfsFonts
    $vfsfontsContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $lib.Critical

    $lib = $Script:LibraryConfig.Html2Pdf
    $html2pdfContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $lib.Critical

    $lib = $Script:LibraryConfig.Html2Canvas
    $html2canvasContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $lib.Critical

    # Download pako for data decompression
    $lib = $Script:LibraryConfig.Pako
    $pakoContent = Get-JSLibrary -Url $lib.Url -Name $lib.Name -Critical $false
    Write-MemoryUsage -Label "JS Libraries"

    # Step 4: Load templates
    Write-Output "Loading templates..."
    $htmlTemplatePath = Join-Path -Path $tempTemplates -ChildPath "dashboard.html"
    $cssTemplatePath = Join-Path -Path $tempTemplates -ChildPath "dashboard.css"
    $jsTemplatePath = Join-Path -Path $tempTemplates -ChildPath "dashboard.js"

    if (-not (Test-Path $htmlTemplatePath)) { throw "Template not found: dashboard.html" }
    if (-not (Test-Path $cssTemplatePath)) { throw "Template not found: dashboard.css" }
    if (-not (Test-Path $jsTemplatePath)) { throw "Template not found: dashboard.js" }

    $htmlTemplate = Get-Content -Path $htmlTemplatePath -Raw
    $cssContent = Get-Content -Path $cssTemplatePath -Raw
    $jsContent = Get-Content -Path $jsTemplatePath -Raw

    # Step 5: Normalize data
    Write-Output "Normalizing data..."
    $tempVulnsPath = Join-Path -Path $tempRoot -ChildPath 'vulns.json'
    $tempPayloadPath = Join-Path -Path $tempRoot -ChildPath 'payload.json.gz'
    $normalizedResult = ConvertTo-NormalizedData -DataPath $tempExports -VulnOutputPath $tempVulnsPath -Machines $machines -AdvancedHuntingData $advancedHuntingData
    $machines = $null
    $advancedHuntingData = $null
    [GC]::Collect()

    # Step 6: Prepare payload for embedding
    Write-Output "Preparing data for embedding..."
    $vulnCount = $normalizedResult.VulnCount
    $deviceCount = $normalizedResult.Lookups.devices.Count
    $cveCount = $normalizedResult.Lookups.cves.Count
    $vulnsFileSize = [math]::Round((Get-Item $normalizedResult.VulnsPath).Length / 1KB, 1)
    Write-Output "  Vulns JSON file: ${vulnsFileSize}KB"

    Write-Output "  Compressing embedded data..."
    $normalizedQuality = $normalizedResult['Quality']
    Write-CombinedPayloadGzip -Lookups $normalizedResult.Lookups -VulnsPath $normalizedResult.VulnsPath -OutputPath $tempPayloadPath
    $normalizedResult = $null
    [GC]::Collect()
    Write-MemoryUsage -Label "Post-Normalize"

    $compressedSize = [math]::Round((Get-Item $tempPayloadPath).Length / 1KB, 1)
    Write-Output "  Compressed: ${compressedSize}KB"

    $lookupsJsonEscaped = ""
    $generatedOnUtc = (Get-Date).ToUniversalTime().ToString('o')
    $dataQualitySectionHtml = @"
    <section class="data-quality-panel" aria-label="Data quality summary">
        <h2>Data Quality</h2>
        <div class="data-quality-grid">
            <div class="data-quality-item"><div class="data-quality-label">Records</div><div class="data-quality-value" id="dqTotalRecords">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Unique Devices</div><div class="data-quality-value" id="dqUniqueDevices">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Unique CVEs</div><div class="data-quality-value" id="dqUniqueCves">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Missing Published Date</div><div class="data-quality-value" id="dqMissingPublished">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Non-YMD Published Date</div><div class="data-quality-value" id="dqNonYmdPublished">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Inverted Seen Ranges</div><div class="data-quality-value" id="dqInvertedRanges">0</div></div>
            <div class="data-quality-item"><div class="data-quality-label">Corrected Seen Ranges</div><div class="data-quality-value" id="dqCorrectedRanges">0</div></div>
        </div>
    </section>
"@
    $dataQualityMeta = @{
        firstLastSwapped = if ($normalizedQuality) { [int]$normalizedQuality.FirstLastSwappedCount } else { 0 }
        generatedOnUtc = $generatedOnUtc
    }
    $dataQualityMetaScript = '<script id="dataQualityMeta" type="application/json">' + ($dataQualityMeta | ConvertTo-Json -Compress) + '</script>'
    Write-MemoryUsage -Label "Post-Compress"

    # Step 8: Assemble final HTML
    Write-Output "Assembling dashboard HTML..."
    $dataFormatMarker = "compressed"
    $pakoScript = if ($pakoContent) { "<script>$pakoContent</script>" } else { "" }

    $segments = @(
        @{ Placeholder = '__CSS_CONTENT__'; Value = $cssContent },
        @{ Placeholder = '__DATA_QUALITY_SECTION__'; Value = $dataQualitySectionHtml },
        @{ Placeholder = '__PAKO_CONTENT__'; Value = $pakoScript },
        @{ Placeholder = '__DATA_FORMAT__'; Value = $dataFormatMarker },
        @{ Placeholder = '__DATA_QUALITY_META_SCRIPT__'; Value = $dataQualityMetaScript },
        @{ Placeholder = '__LOOKUPS_DATA__'; Value = $lookupsJsonEscaped },
        @{ Placeholder = '__VULNS_DATA__'; Base64FilePath = $tempPayloadPath },
        @{ Placeholder = '__CHARTJS_CONTENT__'; Value = $chartJsContent },
        @{ Placeholder = '__PDFMAKE_CONTENT__'; Value = $pdfmakeContent },
        @{ Placeholder = '__VFSFONTS_CONTENT__'; Value = $vfsfontsContent },
        @{ Placeholder = '__HTML2PDF_CONTENT__'; Value = $html2pdfContent },
        @{ Placeholder = '__HTML2CANVAS_CONTENT__'; Value = $html2canvasContent },
        @{ Placeholder = '__JS_CONTENT__'; Value = $jsContent }
    )
    $cssContent = $null
    $jsContent = $null
    $lookupsJsonEscaped = $null
    $pakoScript = $null
    $chartJsContent = $null
    $pdfmakeContent = $null
    $vfsfontsContent = $null
    $html2pdfContent = $null
    $html2canvasContent = $null

    $dashboardOutputPath = Join-Path -Path $tempDashboards -ChildPath "VulnerabilityDashboard.html"
    Write-TemplatedHtml -Template $htmlTemplate -Segments $segments -OutputPath $dashboardOutputPath
    $htmlTemplate = $null
    $segments = $null
    [GC]::Collect()

    $finalSize = [math]::Round((Get-Item $dashboardOutputPath).Length / 1MB, 2)
    Write-Output "  Dashboard generated: ${finalSize}MB"
    Write-MemoryUsage -Label "Post-Assembly"

    # -----------------------------------------------------------------
    # Stage E: Export results
    # -----------------------------------------------------------------
    Write-Output "`n--- Stage E: Export ($Export) ---"

    switch ($Export) {
        'BlobStorage' {
            Export-ToBlobStorage `
                -AccountName $StorageAccountName `
                -StorageToken $storageToken `
                -ExportsPath $tempExports `
                -DashboardPath $dashboardOutputPath `
                -LegacyMachineBlobNames $legacyMachineBlobs `
                -LegacyAdvancedHuntingBlobNames $legacyAdvancedHuntingBlobs `
                -LegacyVulnerabilityBlobNames $legacyVulnerabilityBlobs `
                -UseGzip $useGzip
        }
        'SharePoint' {
            # Still upload to blob as primary, then also to SharePoint
            Export-ToBlobStorage `
                -AccountName $StorageAccountName `
                -StorageToken $storageToken `
                -ExportsPath $tempExports `
                -DashboardPath $dashboardOutputPath `
                -LegacyMachineBlobNames $legacyMachineBlobs `
                -LegacyAdvancedHuntingBlobNames $legacyAdvancedHuntingBlobs `
                -LegacyVulnerabilityBlobNames $legacyVulnerabilityBlobs `
                -UseGzip $useGzip
            Export-ToSharePoint -DashboardPath $dashboardOutputPath
        }
        'StaticWebApp' {
            Export-ToBlobStorage `
                -AccountName $StorageAccountName `
                -StorageToken $storageToken `
                -ExportsPath $tempExports `
                -DashboardPath $dashboardOutputPath `
                -LegacyMachineBlobNames $legacyMachineBlobs `
                -LegacyAdvancedHuntingBlobNames $legacyAdvancedHuntingBlobs `
                -LegacyVulnerabilityBlobNames $legacyVulnerabilityBlobs `
                -UseGzip $useGzip
            Export-ToStaticWebApp -DashboardPath $dashboardOutputPath
        }
    }

    # -----------------------------------------------------------------
    # Cleanup
    # -----------------------------------------------------------------
    Write-Output "`n--- Cleanup ---"
    if (Test-Path $tempRoot) {
        Remove-Item -Path $tempRoot -Recurse -Force
        Write-Output "  Temporary files cleaned up"
    }

    # -----------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------
    Write-Output "`n========================================"
    Write-Output "  Pipeline Complete!"
    Write-Output "========================================"
    Write-Output "  Vulnerabilities: $vulnCount"
    Write-Output "  Devices: $deviceCount"
    Write-Output "  CVEs: $cveCount"
    Write-Output "  Dashboard size: ${finalSize}MB"
    Write-Output "  Export target: $Export"
    Write-Output "  Completed: $(([datetime]::UtcNow).ToString('yyyy-MM-dd HH:mm:ss')) UTC"
}
catch {
    Write-Output "========================================"
    Write-Output "  Pipeline Failed!"
    Write-Output "========================================"
    Write-Output "Error: $_"
    Write-Output "Stack trace:"
    Write-Output $_.ScriptStackTrace

    # Cleanup on failure
    if ($tempRoot -and (Test-Path $tempRoot)) {
        Remove-Item -Path $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }

    throw
}
